### ISSUE TITLE
PHP Fatal Error – yii\base\ErrorException  Class 'BxSlider' not found

### ISSUE THREAD

**Issue by hdushku** [yii2mod/yii2-bx-slider#1]
Nice extension!

PHP Fatal Error – yii\base\ErrorException
Class 'BxSlider' not found

**Comment by disem** [comment]
If you're trying to run example i assume that you didn't include namespace into use statements.
Try `echo yii2mod\bxslider\BxSlider::widget([` and everything should work fine.

**Comment by hdushku** [comment]
Now its ok but showing another error:
PHP Fatal Error – yii\base\ErrorException
Class 'JsExpression' not found

**Comment by dmitry-semenov** [comment]
Same for that class, use `yii\web\JsExpression` :)

**Comment by disem** [comment]
Same for that class, use `yii\web\JsExpression` :)

**Comment by hdushku** [comment]
Working ok ;-)
Thank you
