### ISSUE TITLE
images displayed on left 

### ISSUE THREAD

**Issue by appdevcor** [yii2mod/yii2-bx-slider#2]
Hi first thank you for your awesome widget, I have problems with images all of them are displayed on left I need to show them in the center how can I do that, is there any option propriety can do that or I need to make some modification in css file please I need help thank you.

**Comment by ihorchepurnyi** [comment]
Hi, can you try the following ways?
- https://github.com/stevenwanderski/bxslider-4/issues/844#issuecomment-110724828
- https://github.com/stevenwanderski/bxslider-4/issues/911#issuecomment-147124364

**Comment by appdevcor** [comment]
Hi, thank's so mutch for your help my problem was solved.

**Comment by ihorchepurnyi** [comment]
You are welcome :)
